DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT,
    BATCH_JOB_EXECUTION_CONTEXT,
    BATCH_STEP_EXECUTION,
    BATCH_JOB_EXECUTION,
    BATCH_JOB_EXECUTION_PARAMS,
    BATCH_JOB_INSTANCE,
    BATCH_JOB_SEQ,
    BATCH_STEP_EXECUTION_SEQ,
    BATCH_JOB_EXECUTION_SEQ,
    BATCH_JOB_INSTANCE_SEQ;

-- =========================
-- SPRING BATCH META TABLES
-- =========================

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT,
    BATCH_JOB_EXECUTION_CONTEXT,
    BATCH_STEP_EXECUTION,
    BATCH_JOB_EXECUTION,
    BATCH_JOB_EXECUTION_PARAMS,
    BATCH_JOB_INSTANCE,
    BATCH_JOB_SEQ,
    BATCH_STEP_EXECUTION_SEQ,
    BATCH_JOB_EXECUTION_SEQ,
    BATCH_JOB_INSTANCE_SEQ;

-- ========= JOB INSTANCE ==========
CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT       NOT NULL PRIMARY KEY,
    VERSION         BIGINT,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    CONSTRAINT UK_BATCH_JOB_INSTANCE UNIQUE (JOB_NAME, JOB_KEY)
) ENGINE = InnoDB;

-- ========= JOB EXECUTION ==========
CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID BIGINT   NOT NULL PRIMARY KEY,
    VERSION          BIGINT,
    JOB_INSTANCE_ID  BIGINT   NOT NULL,
    CREATE_TIME      DATETIME NOT NULL,
    START_TIME       DATETIME DEFAULT NULL,
    END_TIME         DATETIME DEFAULT NULL,
    STATUS           VARCHAR(10),
    EXIT_CODE        VARCHAR(20),
    EXIT_MESSAGE     VARCHAR(2500),
    LAST_UPDATED     DATETIME DEFAULT NULL,
    CONSTRAINT FK_JOB_EXEC_INSTANCE FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
) ENGINE = InnoDB;


-- ========= JOB EXECUTION PARAMS ==========
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID BIGINT       NOT NULL,
    PARAMETER_NAME   VARCHAR(100) NOT NULL,
    PARAMETER_TYPE   VARCHAR(100) NOT NULL,
    PARAMETER_VALUE  VARCHAR(2500),
    IDENTIFYING      CHAR(1)      NOT NULL,
    CONSTRAINT FK_JOB_EXEC_PARAMS FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE = InnoDB;

-- ========= STEP EXECUTION ==========
CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  BIGINT       NOT NULL PRIMARY KEY,
    VERSION            BIGINT       NOT NULL,
    STEP_NAME          VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID   BIGINT       NOT NULL,
    START_TIME DATETIME DEFAULT NULL,
    END_TIME DATETIME DEFAULT NULL,
    STATUS             VARCHAR(10),
    COMMIT_COUNT       BIGINT,
    READ_COUNT         BIGINT,
    FILTER_COUNT       BIGINT,
    WRITE_COUNT        BIGINT,
    READ_SKIP_COUNT    BIGINT,
    WRITE_SKIP_COUNT   BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT     BIGINT,
    EXIT_CODE          VARCHAR(20),
    EXIT_MESSAGE       VARCHAR(2500),
    LAST_UPDATED       DATETIME,
    CREATE_TIME        DATETIME,
    CONSTRAINT FK_STEP_EXEC_JOB_EXEC FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE = InnoDB;

-- ========= STEP EXECUTION CONTEXT ==========
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT FK_STEP_EXEC_CTX FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
) ENGINE = InnoDB;

-- ========= JOB EXECUTION CONTEXT ==========
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT FK_JOB_EXEC_CTX FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE = InnoDB;

-- ========= SEQUENCE TABLES ==========
CREATE TABLE BATCH_STEP_EXECUTION_SEQ
(
    ID         BIGINT  NOT NULL PRIMARY KEY,
    UNIQUE_KEY CHAR(1) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION_SEQ
(
    ID         BIGINT  NOT NULL PRIMARY KEY,
    UNIQUE_KEY CHAR(1) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE BATCH_JOB_INSTANCE_SEQ
(
    ID         BIGINT  NOT NULL PRIMARY KEY,
    UNIQUE_KEY CHAR(1) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE BATCH_JOB_SEQ
(
    ID         BIGINT  NOT NULL PRIMARY KEY,
    UNIQUE_KEY CHAR(1) NOT NULL
) ENGINE = InnoDB;

-- ========= SEQUENCE INITIAL VALUES ==========
INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY)
VALUES (1, '0');
INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY)
VALUES (1, '0');
INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY)
VALUES (1, '0');
INSERT INTO BATCH_JOB_INSTANCE_SEQ (ID, UNIQUE_KEY)
VALUES (1, '0');